export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const SHOW_ADDED_NOTIFICATION = 'SHOW_ADDED_NOTIFICATION'
export const SHOW_ALREADY_NOTIFICATION = 'SHOW_ALREADY_NOTIFICATION'
export const SHOW_LOGOUT_NOTIFICATION = 'SHOW_LOGOUT_NOTIFICATION'
export const SHOW_DELETED_NOTIFICATION = 'SHOW_DELETED_NOTIFICATION'
export const SHOW_EMAIL_NOT_FOUND_NOTIFICATION =
  'SHOW_EMAIL_NOT_FOUND_NOTIFICATION'
export const SHOW_RESEND_TOKEN_NOTIFICATION = 'SHOW_RESEND_TOKEN_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'
